[platformio]
default_envs = node

[env] ; Base environment for shared settings
platform = espressif32
board = mhetesp32devkit
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit BMP280 Library @ ^2.6.8
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit MPU6050 @ ^2.2.6

; ============================
; 1. MAIN APPLICATION
; ============================
[env:node]
build_src_filter = +<*> -<../examples/>
build_flags = -Wall -DPIPSURVIVOR_RADIO_RYLR998
; upload_port = COM8 ; Uncomment to pin to a specific port
; monitor_port = COM8


; ============================
; 2. HARDWARE TESTS
; ============================

[env:test_barometer]
build_src_filter = +<../examples/bmp280_altitude_test/> -<*>

[env:test_alert_detection]
build_src_filter = +<../examples/alert_detection_test/> -<*>

[env:test_tzt_water_level]
build_src_filter = +<../examples/tzt_water_level_test/> -<*>

[env:test_tzt_submersion]
build_src_filter = +<../examples/tzt_submersion_test/> -<*>

[env:test_mpu6050_accel]
build_src_filter = +<../examples/mpu6050_accel_test/> -<*>

[env:test_uart]
build_src_filter = +<../examples/uart_radio_detect/> -<*>

[env:test_sensor_combo]
build_src_filter = +<../examples/sensor_combo_test/*>
build_flags = -Wall
